### ISSUE TITLE
Bottom sheet becomes dark color in Dark mode

### ISSUE THREAD

**Issue by Trubianov** [Kaww/BottomSheet#6]
My app uses `preferredColorScheme(.light)` but  it doesn't work for if my phone/simulator in dark mode for bottom sheet, the rest of the app works in Light mode. Please assist. 
P.S. already tried manually set  preferredColorScheme(.light) for bottom sheet view.

**Comment by Kaww** [comment]
Thanks for the feedback ! I'll will fix that ASAP !

**Comment by Kaww** [comment]
@Trubianov, fixed in #7.

**Comment by Anton-Trubianov** [comment]
I still don't see this param. Using SPM, on main branch. What i should do, new init with this parameter appear ?

**Comment by Kaww** [comment]
I added the support [here](https://github.com/Kaww/BottomSheet/commit/a84d1adf3cab52b6ac0053e28967523588d08b1b).
But maybe Xcode doesn't see the update as I forgot to change the version number. You could try in Xcode to clear SPM cache and re-fetch lastest version. Or remove and re-add the package.
